/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_wasmtask_content: (a: number) => [number, number];
export const __wbg_get_wasmtask_id: (a: number) => [number, number];
export const __wbg_get_wasmtask_is_completed: (a: number) => number;
export const __wbg_get_wasmtask_last_modified: (a: number) => number;
export const __wbg_set_wasmtask_content: (a: number, b: number, c: number) => void;
export const __wbg_set_wasmtask_id: (a: number, b: number, c: number) => void;
export const __wbg_set_wasmtask_is_completed: (a: number, b: number) => void;
export const __wbg_set_wasmtask_last_modified: (a: number, b: number) => void;
export const __wbg_versaengine_free: (a: number, b: number) => void;
export const __wbg_wasmtask_free: (a: number, b: number) => void;
export const reverse_string: (a: number, b: number) => [number, number];
export const versaengine_apply_task: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const versaengine_delete_task: (a: number, b: number, c: number) => [number, number, number, number];
export const versaengine_get_doc_json: (a: number) => [number, number];
export const versaengine_get_tasks: (a: number) => [number, number];
export const versaengine_merge_update: (a: number, b: number, c: number) => [number, number];
export const versaengine_new: (a: number, b: number) => number;
export const versaengine_snapshot: (a: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
